### ISSUE TITLE
__APPLE__ macros, Mac support?

### ISSUE THREAD

**Issue by javf88** [BabbleSim/native_simulator#3]
Hi,

First things first, what an interesting piece of technology is native simulator. I ended up here due to the zephyr project, as I am exploring it.

I have seen that native_simulator has some macOS macros. Is it possible to run it on a Mac?

kind regards,
Jorge

**Comment by aescolar** [comment]
Hi @javf88.
It is not possible to use it on MacOS due to fundamental differences between macOS and other typical Unixes.
(There is no __APPLE__ macros on its source)

**Comment by javf88** [comment]
Ok, I was expecting this. About the macros, I should have added them in a rush many months ago to assess portability.

it just puzzled me that they were on my working branch and I couldn’t remember adding them.
